#deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: prod
    app: ic-webapp
  name: ic-webapp
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp

  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - image: choco1992/ic-webapp:v1.0
        name: ic-webapp
        env:
        - name: ODOO_URL
          value: http://172.28.128.137:30069/
        - name: PGADMIN_URL
          value: http://172.28.128.137:30050/
        ports:
        - containerPort: 8080
          name: ic-webapp

#namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: "ic-webapp"
  labels:
    env: prod

#nodeport
---
apiVersion: v1
kind: Service
metadata:
  name: ic-webapp
  labels:
    app: ic-webapp
    env: prod
  namespace: ic-webapp
spec:
  type: NodePort
  selector:
    app: ic-webapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
